### ISSUE TITLE
Create table basic 

### ISSUE THREAD

**Issue by thang148** [react-page/react-page#1100]
How to create table.
Edit data in table by rich text editing slate.
Thank you!

**Comment by SaadBazaz** [comment]
This is much needed. Any update?

**Comment by macrozone** [comment]
currently no update. 

Tables in Rich-text-editors are hard to implement right and tables are tricky in responsive-designs.

i personally would advice to create custom CellPlugins instead for specific table-like usecases. Ask your customers whether they really need a generic table or whether they have more specific use cases. For Example they may actually want to display specific data in a table-like fashion, data that already exists somehwere. So its far better to fetch this data and render it as a table in a custom CellPlugin instead of having your users fiddling with a table.


Having said that, there are examples of tables in slate. Also there is actually a community plugin https://github.com/junminahn/react-page-plugins, but i am not sure how up-to-date it is (also it could increase your bundle size given its direct dependencies)
