### ISSUE TITLE
Material-UI Error

### ISSUE THREAD

**Issue by mlnima** [react-page/react-page#1123]
I get this error :  

Material-UI: the createMuiTheme function was renamed to createTheme.
You should use `import { createTheme } from '@material-ui/core/styles'`

I did not use Material-UI on the whole project, only installed it because of @react-page, could you please help me with this error.

**Comment by macrozone** [comment]
@mlnima that is just a warning, make sure to install material-ui version 4 until https://github.com/react-page/react-page/issues/1085 is resolved

**Comment by mlnima** [comment]
here is packageJson   
"@material-ui/core": "^4.12.3",
"@material-ui/icons": "^4.11.2",
"@material-ui/styles": "^4.11.4",

anyway you are right :), production is fine on https://02dev.com/post/learn/6181a406a3c5fd928f151e93

**Comment by sdotter** [comment]
yeah...  line 94 should be a console.warn not console.error... but glad its not an error :p

**Comment by macrozone** [comment]
i actually used the new `createTheme` import at some point, but then it broke in one of my projects, because there i had a too low material-ui version.

ideally, we could just bundle our own material ui version, so that it does not conflict with the one that devs are using, but material 4 did not allow that (or lead to bugs if you did). Thats why its a peerDependency currently

maybe material ui 5 does not have that problem anymore.
