### ISSUE TITLE
"Invariant Failed" on Text plugin

### ISSUE THREAD

**Issue by SaadBazaz** [react-page/react-page#1250]
**Describe the bug**
Whenever I create a Text cell, the following error occurs:
<img width="1550" alt="Screenshot 2022-11-10 at 12 32 11 AM" src="https://user-images.githubusercontent.com/51885228/200924103-1841b01b-258e-46d4-9200-450e71e5bc4a.png">

In text:
```
Error: Invariant failed
    at f (5481.1bde9ef43b6d5d74c44a.js:1:1215)
    at 5481.1bde9ef43b6d5d74c44a.js:1:23701
    at Object.useMemo (framework-e12e56e0b8a76d261551.js:1:66202)
    at t.useMemo (framework-e12e56e0b8a76d261551.js:1:126311)
    at Xe (5481.1bde9ef43b6d5d74c44a.js:1:23580)
    at ro (framework-e12e56e0b8a76d261551.js:1:60237)
    at Hu (framework-e12e56e0b8a76d261551.js:1:112695)
    at Pi (framework-e12e56e0b8a76d261551.js:1:99869)
    at xi (framework-e12e56e0b8a76d261551.js:1:99797)
    at _i (framework-e12e56e0b8a76d261551.js:1:99660)
```

**To Reproduce**
1. Install the "Table" plugin - https://www.npmjs.com/package/@react-page-plugins/slate-table
2. Click on "Text"
3. See error

**Expected behavior**
The text cell should work as usual.

**Desktop:**
 - OS: Linux / Unix
 - Browser: all

**Smartphone:**
 - Device: all

**Additional context**
I've added a modified version of Slate Table. Also, I had to npm install by force.

**Comment by macrozone** [comment]
hi @SaadBazaz , please report this to the https://github.com/junminahn/react-page-plugins repository, we do not maintain this plugin

**Comment by macrozone** [comment]
> > hi @SaadBazaz , please report this to the https://github.com/junminahn/react-page-plugins repository, we do not maintain this plugin
> 
> This happens in the "Text" plugin. Isn't that managed by ReactPage?

by your description, this happens when you install `https://www.npmjs.com/package/@react-page-plugins/slate-table` so its related to that. It maybe because that plugin installs another version of slate, so you may cannot use it alongside our own rich-text-plugin. If you remove https://www.npmjs.com/package/@react-page-plugins/slate-table, does it still happen?

Also I cannot recommend that plugin as it will blow up your bundle size even in readonly. Additionally i do not endorse plugin, that re-invent the wheel. Table support has been requested multiple times, and I would have wished that someone would make an effort to bring it to the official react-page slate-plugin instead of re-creating the plugin somewhere else.

**Comment by macrozone** [comment]
i would recommend to post an issue in that repository, showing a reproduction.
