### ISSUE TITLE
Convert from HTML convenience function

### ISSUE THREAD

**Issue by Discordius** [react-page/react-page#403]
The current slate component has an `importFromHTML` function that is called in a lot of the examples, but it is not really exposed via any API. So right now if I want to initialize an editable from an HTML String, I have to create my own State-JSON-object that has a cell with the slate plugin and whose state is just `importFromHTML: "<div> ... </div>`, which seems like a lot of hassle. 

A convenience function that would be called with something like: 

`editor.trigger.editables.add(editor.utilities.convertFromHTML(HTMLString)) `

Would be a lot nicer

**Comment by arekkas** [comment]
The issue here is that we can't really import layouts, which is why this isn't currently supported. One possibility would be to have a helper that simply creates one text cell and imports HTML.

**Comment by Discordius** [comment]
Yeah, at least in my use-cases I am looking at simple text-markup in HTML. So that would be sufficient for me. Maybe we could name the function something that makes that limitation clear, maybe `importHTMLTextMarkup()` or something like that.

**Comment by YizYah** [comment]
@arekkas Can you please elaborate: why can't we set up the editor to import layouts?

Is there any possibility of converting HTML to react and then importing the react components into the editor?

**Comment by arekkas** [comment]
The problem is that no layout grid is the same across a number of websites. One html snippet could use bootstrap grid, another uses material ui grid, another one uses flexbox grid, and another one uses it's own mechanism. Additionally, HTML is primarily a language for displaying content so it's impossible to rely on developers doing sane things with their html. One developer might nest 3 divs in order to create a layout, another one uses a table.

As you see, it's very difficult to analyze layouts and create a sane and understandable model from it.

**Comment by YizYah** [comment]
Thanks @arekkas !

I have a thought: what if we simplified the task by allowing conversion from a single grid type?

[The case is that we want to allow our users to create their own HTML documents and import them into the editor.  We could make any stipulations that we'd like.  For instance, we could say that you can import an HTML document using a bootstrap grid for layout.]

**Comment by arekkas** [comment]
Then we would only serve one use case, which is using bootstrap for grid layout. We need to solve this generically or it's not really worth the work.

In your use case, if you know that people use only one way to write the mark up, you could easily process the html to a json object yourself and give that to the editor.

**Comment by YizYah** [comment]
@arekkas any tips on how best to process the html to a json object?  (You mean programatically  or manually?)

BTW, I do see huge benefits to serving the one use case:
(1) you'd make the ORY editor directly accessible to a common format towards which people like me could steer users
(2) it would be a basis for a general solution, because we could use external converters if they exist or expand the solution slowly to accept other formats.
(3) indirectly you'd be supporting moving the world toward a standard for HTML layouts.  (As the Ory editor hopefully gets widely adopted, the supported format will come to be favored.)

In general, supporting input from HTML, no matter what constraints you demand, would vastly expand the usefulness of the editor!

**Comment by Alderr** [comment]
@arekkas Any updates on this?

**Comment by arekkas** [comment]
Sorry, not really. The same limitations apply.

**Comment by macrozone** [comment]
this is now possible:

```

import slate from '@react-page/plugins-slate';

const mySlate = slate(/* customize slate, e.g. add custom plugins */)

const slateState = mySlate.htmlToSlate(htmlString);

```

it also honors all defined plugins properly
