### ISSUE TITLE
endDrag() is not called when plugin is dropped

### ISSUE THREAD

**Issue by AwolDes** [react-page/react-page#472]
Hey Guys

I'm currently using ORY for building a CMS at work, and I've made a plugin with [ChartJS](https://www.npmjs.com/package/react-chartjs-2) so users can drag and drop a graph in like the following:
![image](https://user-images.githubusercontent.com/9693812/30948873-4f5f40e6-a456-11e7-8b80-3c933be4fefc.png)

The bug is triggered when another plugin is dragged and snapped on to the bottom or top edge of the Chart plugin. This causes the Chart plugin to re-render, and the `endDrag()` function in `ory-editor-ui/Toolbar/Draggable/helpers/index.js` does not get called so the editor is never told that a drag event has finished which leads to this error.
![image](https://user-images.githubusercontent.com/9693812/30948964-ef19d5d8-a456-11e7-819e-95f5f1f24cb8.png)
I've tracked it down to the ChartJS package running the `componentDidUpdate()` function, which is looks like this:
![image](https://user-images.githubusercontent.com/9693812/30949025-602202b4-a457-11e7-9a0a-c1e5cef11d67.png)
When the chart is rendered, it uses a `<canvas>` element which ORY might not like?

Any help would be greatly appreciated! Cheers guys :)

**Comment by arekkas** [comment]
Hm, can you check if there's a div layover over the canvas element? We create those divs (position absolute spanning the whole cell) in dnd mode.

Can you also investiage *why* chartjs is redrawing?

**Comment by AwolDes** [comment]
There is a div positioned over the canvas element (with the class `ory-cell-draggable-overlay ory-cell-draggable-leaf`). 

ChartJS is redrawing because of its `shouldComponentUpdate` function. Although I'm not sure why, because the parent component I have uses the following function, which which means the graph shouldn't update unless there's new data.
```
shouldComponentUpdate(nextProps) {

        if (nextProps === this.props) {
            return false;
        }

        return true;
   }
``` 

I recorded a gif for a better demonstration of the bug.
![demo](https://user-images.githubusercontent.com/9693812/31104455-63e8ec6a-a820-11e7-91cc-0375d59f3d79.gif)

**Comment by AwolDes** [comment]
Just tested it with a colleague on OSX (I'm on Ubuntu 16.04). It works on his machine on the same browser (Google Chrome) and browser version (61.0.3163).

**Comment by arekkas** [comment]
Ok, that's really weird. Is there some way you could share this example? I could check it on my browser.

I think this issue is caused by the following:

* onDrag starts
* hover effects on chartjs element
* on cancel, chartjs is being re-rendered, causing the previous element to be replaced
* because the original element does not exist any more, end drag is not executed properly

It's possible that this works on other machines due to latency. If the rerender process is slower than the onDragEnd process, then it works fine. If it's the other way around, the error is thrown.

**Comment by AwolDes** [comment]
Yeah it seems to be some sort of race condition. I've just tested it on our staging build, and it works. So it seems it just happens on my machine, on a local build. If I find a reliable way to consistently get it to break, this issue can be reopened but for now it seems to be solved.

**Comment by arekkas** [comment]
Ok, thank you for the update! If you find a way to resolve it let me know!

**Comment by arekkas** [comment]
Ok this is strange, I was able to reproduce this on the demo page in chrome without any special plugin. Reopening.

**Comment by arekkas** [comment]
So I investigated a bit and what struck my eye was this warning:

<img width="918" alt="bildschirmfoto 2017-10-16 um 12 26 18" src="https://user-images.githubusercontent.com/3372410/31607599-3dd8c0de-b26d-11e7-8c5f-0ced1792818b.png">

Having said that, this doesn't seem to be the root cause (because sometimes drops still work despite that warning), but it's an indicator.

**Comment by AwolDes** [comment]
That is really weird... How did you reproduce it? Could this be a bug within the `react-dnd` library, or just how it's being implemented with the editor plugins?

**Comment by crackcomm** [comment]
It seems to be the same thing:
```
Uncaught Error: Cannot call hover after drop.
at r (browser.js:40)
at e.c (dragDrop.js:111)
at Object.hover (DragDropManager.js:92)
at e.value (HTML5Backend.js:495)
```
