### ISSUE TITLE
Intercepting Store Dispatch Actions

### ISSUE THREAD

**Issue by KamesCG** [react-page/react-page#491]
I've created a plugin, which connects with my applications primary Redux store.

After inspecting the Redux Chrome Extension, I noticed the Editor Redux store was intercepting my dispatched actions.

Is there a recommended approach to dispatching actions to a different Redux Store from within the Editor instance?

**Comment by arekkas** [comment]
The issue here is that we have two redux stores where the plugin is wrapped in the editor's redux store but expects your redux store. This obviously can't work as redux is using react contexts which are simply overwritten when wrapping multiple `react-redux` providers.

I feared that this day will come sooner or later and am open to hear ideas how to resolve this. One thing I've played with in my mind is something we did with `redux-saga-fetch` where we added a [reducer "enhancer"](https://github.com/ory/redux-saga-fetch/blob/master/src/index.js#L123). That basically added a new reducer responsible for handling the state of the library. We might be able to do the same with the editor's reducer (we could use only one reducer key and write sub reducer to reduce the amount of reduce reduce reduce reduce...lol sorry, too much reduce. anyways, it would be possible to handle this in a sane way).

However, it would require some refactoring and planning and also a way to work with the current set up where a store is created for you.

I'm open to ideas and PRs, although the latter might result in easily in 10-20 iterations until we get it straight.

**Comment by KamesCG** [comment]
Wow, thanks for such a quick reply :) I was hoping that wasn't going to be the answer...

My use is kind'of particular. I only need to access my Redux store at the Display level in my plugin. 

First instinct was to wrap each component, at the display layer, with the the primary Store provider. Providing my core application component with access to the correct Store to fetch data.

plugin
- index.js 
-- Component
--- index.js
--- Form
---- index.js
--- Display <---- Wrap the store provider here.
---- index.js

**Comment by KamesCG** [comment]
Could we add an alternative store in the plugin settings?

```
export default {
  Component,
  storeAlt: StoreProvider <--------- New Store
  name: 'eidenai/ethereum/blockchain/block',
  version: '0.0.1',
  IconComponent: <SVG svg={svg.ethereum} />,
  text: 'Ethers | Blockchain Block',
  description: 'Request an Ethereum Block',
  handleFocus: (props, source, ref) => {
    if (!ref) {
      return
    }
    setTimeout(() => ref.focus())
  }
}
```

Then do something tricky to allow components to hook into that during render?

**Comment by arekkas** [comment]
> Could we add an alternative store in the plugin settings?

Not sure that would work

> First instinct was to wrap each component, at the display layer, with the the primary Store provider. Providing my core application component with access to the correct Store to fetch data during the editing stage.

Did you try that? It *could* work!

**Comment by KamesCG** [comment]
I'm in the process of cleaning up my application codebase.

Next week I'm going to dive into the Editor more. I'll let you know my discoveries.

>Not sure that would work

Simply, because it adds gets to messy? Do you know something I don't?

What if another part of my component wants access to my application store? Like the Form when I am editing? I don't want to inject the store at multiple locations in the component. Why not just inject at the highest level and pass down as needed?

**Comment by arekkas** [comment]
> Simply, because it adds gets to messy? Do you know something I don't?

Yes exactly, it would become harder to solve in a task that, as you already proposed, could be solved that way. The ORY Editor shouldn't really have a concept of what the plugin's components are doing, other than exposing an API to interact with the editor's core.

> What if another part of my component wants access to my application store? Like the Form when I am editing? I don't want to inject the store at multiple locations in the component. Why not just inject at the highest level and pass down as needed?

That can be easily solved by wrapping your component yourself, I don't see a reason why this would be the task of the Editor!

**Comment by KamesCG** [comment]
Understood. I wasn't sure if you wanted to integrate store management into ORY.

Separation of concerns  - Affirmative Captain. Good path forward.

**Comment by arekkas** [comment]
:)

**Comment by davidfurlong** [comment]
this has been solved, you can now pass your own redux store to ory
