### ISSUE TITLE
HTMLRenderer | rendering of empty paragraphs

### ISSUE THREAD

**Issue by KillerCodeMonkey** [react-page/react-page#496]
There is an issue if you are using empty paragraphs as spaceholder

**Steps to reproduce:**

1. Add a textbox
2. Enter some text + Press enter multiple times to add space
3. Render the content with the HTMLRenderer
4. the space is gone

**Version:**
- 0.2.25

**Problem:**
Ory adds something like this:

```
<p data-key="115">
  <span data-key="114">
    <span data-offset-key="114-0"><br></span>
  </span>
</p>
```

<img width="782" alt="bildschirmfoto 2017-12-08 um 10 52 44" src="https://user-images.githubusercontent.com/2264672/33760475-02c88cb4-dc06-11e7-90f6-745cf3388290.png">

After the renderer processed the content only empty p-tags are left:
```
<p></p>
```

<img width="525" alt="bildschirmfoto 2017-12-08 um 10 51 28" src="https://user-images.githubusercontent.com/2264672/33760479-0700f87a-dc06-11e7-8031-9c7effa77af8.png">

**Possible Workaround:**
- Use shift+enter to add linebreaks instead of empty paragraphs

**Comment by arekkas** [comment]
I think the problem is that the p tags are considered empty, so nothing is included. The span/br thing is included during editing so it's possible to put the cursor in that line. In rendering mode however, this hack is not included as it's not necessary, leading to an empty p tag and thus the browser not displaying any space for it as it's empty.

I think one possibility is maybe setting min-height or using the work around you mentioned. I'm not sure if newer slate versions have solved this.

**Comment by KillerCodeMonkey** [comment]
Yeah, but See the workaround is okay for me AS the developer. As an enduser
i would expect, that everything in rendered mode looks exactly like in
editmode. Thats the thing of something like a wysiwyg editor. And this
should work out of the box. Without stripping the p Tag content.

Am 08.12.2017 1:30 nachm. schrieb "Aeneas" <notifications@github.com>:

I think the problem is that the p tags are considered empty, so nothing is
included. The span/br thing is included during editing so it's possible to
put the cursor in that line. In rendering mode however, this hack is not
included as it's not necessary, leading to an empty p tag and thus the
browser not displaying any space for it as it's empty.

I think one possibility is maybe setting min-height or using the work
around you mentioned. I'm not sure if newer slate versions have solved this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ory/editor/issues/496#issuecomment-350252166>, or mute
the thread

**Comment by arekkas** [comment]
As I mentioned above you could solve this easily with a CSS rule. Personally, I think using empty lines to layout is malpractice and leads to shitty readability on mobile which is why I think it is ok to strip them in the standard version, since it is possible to just write one CSS rule changing this.

**Comment by KillerCodeMonkey** [comment]
I know and i solved it with a CSS rule, but i thought ory is there to give
the user something like wysiwyg for a static site. So i expected it should
be the standard behavior to transform the look of the editor view to the
rendered result. ;)






Am 08.12.2017 3:51 nachm. schrieb "Aeneas" <notifications@github.com>:

As I mentioned above you could solve this easily with a CSS rule.
Personally, I think using empty lines to layout is malpractice and leads to
shitty readability on mobile which is why I think it is ok to strip them in
the standard version, since it is possible to just write one CSS rule
changing this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ory/editor/issues/496#issuecomment-350281756>, or mute
the thread

**Comment by arekkas** [comment]
The editor is specifically designed to not make the same mistakes that we had for the last 10 years with things like TinyMCE or CKEditor. We wanted to give freedoms, but also keep restraints. Writing digital content requires some experience and understanding of how things work on mobile. Using tables for layout (looking at you TinyMCE) or having 10 newlines so things align is not how we create content that works everywhere. Compromises have to be made, this is definitely one of them.

**Comment by KillerCodeMonkey** [comment]
Goooooood ckeditor... Memories and flashbacks :D. So i am using quill for
those reasons.

I und erstand you, but i think it is missleading , if even the preview in
the editor mode shows the space and rendered result not.

My Problem is not to add this CSS rule. And i am totally with you and the
mobile first approach. But the editor should show somewhere some how the
real rendered result. Without making changes in my own.


Am 08.12.2017 4:06 nachm. schrieb "Aeneas" <notifications@github.com>:

**Comment by arekkas** [comment]
That's a good point. Newlines are particularly tricky because without the br tag in edit mode, it will be impossible to actually click on the line. With an empty editor it will not even be possible to select the text area. One possibility would be to have a rule that adds a br tag to empty paragraphs, but I don't think I'd like to see it as default.

**Comment by macrozone** [comment]
close due to inactivity. Please reopen if you still experience problems with it!
