### ISSUE TITLE
Problem in a tutorial in the docs

### ISSUE THREAD

**Issue by sakhmedbayev** [react-page/react-page#521]
I am trying to follow a tutorial [here](https://ory.gitbooks.io/editor/content/tutorials.html#reactjs-example)

Instead of being able to add a new text element or any other elements I can see only this message

"This is the default plugin from the core package. To replace it, set the "defaultPlugin" value in the editor config."

I can click on this text and it turns to the input element but I cannot edit it. Is what I should see?

**Comment by arekkas** [comment]
Make sure to pass the plugins, like here: https://github.com/ory/editor/blob/master/examples/src/index.js#L82-L99

**Comment by toonjanssens** [comment]
I had the same issue. Solved by adding a defaultPlugin like this:

```javascript
const editor = new Editor({
    plugins: plugins,
    defaultPlugin: slate(),
    editables: [editable],
});
```

**Comment by PeterKottas** [comment]
Same here, apparently the reason for this is the tutorial provides it's content, however if you create empty state, it will add the default plugin right away so that you can start typing. That's why you need to provide default. This option however seems undocumented. It should probably be added to docs.
