### ISSUE TITLE
Storing state data and backward compatibility

### ISSUE THREAD

**Issue by Senneer** [react-page/react-page#666]
Hi there! I've found similar but closed issue about data storing. https://github.com/aeneasr/ory-editor/issues/572
I wonder how would you handle this problem? The case with json as string seems ok, but what about backward compatibility? Will the json structure be changed some time?

**Comment by davidfurlong** [comment]
I expect any future changes will either include a migration script or be backwards compatible. Any backwards incompatible changes to official plugins will likely involve either a new plugin name (so that they are backwards compatible, you just need to include both the new and old plugin) or similarly have migration functions
