### ISSUE TITLE
Can we remove DCO?

### ISSUE THREAD

**Issue by davidfurlong** [react-page/react-page#678]

**Comment by macrozone** [comment]
we should also think about the copyright header in every file.

Of course the original copyright and licence still applies, but its probably better to handle that in LICENCE.md or so, because this header licences are a) not really required b) hard to manage (do i have to add my name if i change a source? what if i copy a file? move a file?, etc.) and c) noisy.

Maybe @aeneasr @ory need to specify of what happens to the licence of this project and how the copyright should be handled. Also i would prefer MIT Licence personally, but just because i am not a lawyer and i don't like bureaucracy ;-)

**Comment by aeneasr** [comment]
Yeah we can remove the license headers. I don't think they're maintained very well anyways.

I would not remove the DCO because if it is removed, we could not switch to MIT without asking every single contributor for permission. I'm fine with MIT or Apache 2.0

**Comment by macrozone** [comment]
> Yeah we can remove the license headers. I don't think they're maintained very well anyways.
> 
> I would not remove the DCO because if it is removed, we could not switch to MIT without asking every single contributor for permission. I'm fine with MIT or Apache 2.0

ok, i think you know better about these topics. But i think the DCO is not checked right? Or is this just a silent agreement?

**Comment by aeneasr** [comment]
Seems like the DCO bot does not work anymore so you are correct, it is currently not enforced.

**Comment by PeterKottas** [comment]
Ok this appears to be somewhat resolved, closing as part of the cleanup.
