### ISSUE TITLE
How to customize `react-page/plugin-slate`

### ISSUE THREAD

**Issue by KemarDarlington** [react-page/react-page#690]
I am trying to do 

```
import InsertImages from 'slate-drop-or-paste-images'

const slatePlugins = [
  InsertImages({
    extensions: ['png'],
    insertImage: (change, file) => {
      return change.insertBlock({
        type: 'image',
        isVoid: true,
        data: { file }
      })
    }
  })
]

const plugins = {
  content: [slate(slatePlugins), spacer, imagePlugin(), video, divider, html5video],
  layout: [
    background({
      defaultPlugin: slate(),
      enabledModes: ModeEnum.COLOR_MODE_FLAG | ModeEnum.GRADIENT_MODE_FLAG,
    }),
  ],
  native,
};

```

And I get

```
Uncaught TypeError: Cannot read property 'commands' of undefined
    at registerPlugin (slate.es.js:11864)
    at slate.es.js:11859
    at Array.forEach (<anonymous>)
    at registerPlugin (slate.es.js:11858)
    at slate.es.js:11859
    at Array.forEach (<anonymous>)
    at registerPlugin (slate.es.js:11858)
    at slate.es.js:11859
    at Array.forEach (<anonymous>)
    at registerPlugin (slate.es.js:11858)
```
In web console.

What is the way to add a community slate plugin into react-page/plugin-slate?

**Comment by 8ctopotamus** [comment]
I see this issue is closed, and I would also like to add custom plugins into Slate. What is the answer here?

**Comment by macrozone** [comment]
@8ctopotamus this has been revampt. It's documented here https://github.com/react-page/react-page/blob/master/docs/plugins/slate.md with some basic example.

you'll find more examples in the examples project, this: (simple example) https://github.com/react-page/react-page/blob/master/examples/src/customSlatePlugin.tsx and this: (a more complex example) https://github.com/react-page/react-page/blob/master/examples/src/katexSlatePlugin.tsx

**Comment by 8ctopotamus** [comment]
Thanks @macrozone  I found the example here: https://github.com/react-page/react-page/blob/master/docs/plugins-slate.md

I would like to implement this table plugin: https://github.com/GitbookIO/slate-edit-table

I followed the example code under "if you want to add an additional plugin, you can use all default plugins like this:"...

```
const slatePlugin = slate(def => ({
  ...def,
  plugins: {
    ...def.plugins,
    simpleTable: {
      simpleTable: SimpleTable()
    }
  }
}))
```

....but it does not work. I assume that later (once working), we would pass this into `slate(slatePlugin )`

By the way, your documentation code is full of bugs. In this snippet, there was a missing parenthesis and a period instead of a comma to separate key:value pairs.

**Comment by macrozone** [comment]
@8ctopotamus unfortunatly, slate has changed vastly internally, so old plugins no longer work. Also our plugin api for slate differs from vanilla slate, because have additional and opnionated features that integrate into the rest of react-page (e.g. bottom toolbar with icons or with form fields)
