### ISSUE TITLE
community chat?

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#696]
might be nice to have a spectrum or slack channel for this project! what do you guys think? should i open a spectrum?

**Comment by fernandobandeira** [comment]
Yeah, feel free to open a spectrum, I think that it works better for big communities like this, we can interact with the community there.

**Comment by andreastoermer** [comment]
Because there is no reaction since 10 days, i started a slack channel.

The URL to join it is https://join.slack.com/t/reactpage/shared_invite/enQtNzA5ODAyMzk0ODg0LWIxZDNiOWUyMWJlZmE5NWQzY2M1ZjQ2YTkxZmFmMmM2MDdkZDE1MzliMTEyYzkyMTJkYTNiNzdmMWNiMzlmODU

 @fernandobandeira When you are only, contact me and i can give you admin access

**Comment by macrozone** [comment]
sorry, wasnt sure about it ;-)

i joined!

**Comment by macrozone** [comment]
i close this as we have now a chat. I added a PR that adds a link to the readme

**Comment by runjak** [comment]
Hi, when trying to use the invite link I've found that slack says that it is no longer active.
The link from the readme doesn't seem to work either.

Is the chat still in use or has it moved elsewhere?

**Comment by macrozone** [comment]
@runjak its not very active, but i could log in. https://reactpage.slack.com/ ?

**Comment by runjak** [comment]
Thanks @macrozone - the link that you gave indeed seems to work. However it is different from the one in the readme ;) I've opened #754 to address this.
