### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by owlblinked** [react-page/react-page#727]
Hello!

What about custom css for page, which we create using builder? Should I create any plugin or how can I create own styles?

**Comment by macrozone** [comment]
@owlblinked the editor itself uses material-ui, but everything else can be styled however you want. 

What exactly do you want to style?

**Comment by owlblinked** [comment]
I want to add custom css to page, which I build. Or have possibility to choose own color of common background and common font.

For example, I have some field where I can add custom css - anything, which I want to use for page - it can be some common rules for theme or removing all margins. I hope you understand me.

**Comment by macrozone** [comment]
@owlblinked can you give some examples?

which elements do you want to give custom css? blocks like image or only text-stuff (headings, paragraphs, etc.)? Also how do you usually style your elements? using css or something like styled-components?

i am asking this, because there are multiple strategies:

- just wrap everything with a class and create a css that modifies what you want
- use your own components in the editor that uses some context (e.g. ThemeProvider from styled-components) for stylings
- use your own components in the editor and extend the schema to take an addition `style` property or whatever which gets used in your components. 

also you can take a look at a very simple example where a custom slate plugin allows to set the color for the text: https://github.com/react-page/react-page/blob/master/examples/src/customSlatePlugin.tsx

**Comment by PeterKottas** [comment]
This is about injecting custom CSS on the editor level via a plugin, not about overriding UI. Imho not a good idea. That's giving people way too much freedom on doing weird stuff. You could technically only inject the rendered styles into a selector that would only select the page itself. But overall this seems a little bit far fetched.
