### ISSUE TITLE
New Plugin-Panel layout

### ISSUE THREAD

**Issue by macrozone** [react-page/react-page#745]
**Is your feature request related to a problem? Please describe.**

The plugin panel currently show layout plugins and content plugins separatly. Content-Plugins just render a component with its controls, while a layout-plugin additionally can contain other plugins.

This is a technical distinction. I currently find myself implementing some teaser-components as layout-plugins, because i want them to contain `slate`-cells where the editor-user can just click into and write, but some plugins are easier to configure with a form-control. For the editor-user, its not clear why some plugins are in the layout section and some are in the content section.

**Describe the solution you'd like**

Instead of give this two categories *layout* and *content*, i would love to be able to define arbitrary categories.

E.g.

```
const myPluginSections = [
{
  title: "Teasers",
  plugins: [... /* list of teaser-plugins or their names */],
},
{
  title: "Media",
  plugins: [... /* list of media-plugins like images, videos, etc. */],
}
// whatever

]
<EditorUI pluginPanelSections={myPluginSections} plugins={...} />
```

You would still need to add all plugins that you will use in the `plugins`-prop. it can even contain more plugins than you show in your plugin-panel, e.g. if you have layout-plugins that place initial children with special configured plugins

**Describe alternatives you've considered**

it would also be possible to unify `pluginPanelSections` and `plugins` into one configuration, if it allow you to define also hidden plugins (or sections). The reason for my proposed soluition is, that it is backwards-compatible. If you don't the define a `pluginPanelSections`, the current categories with layout and content will be used.

**Additional context**

Some ideas for the future:

- we could also get crazy and provide previews of the plugins in the panel! e.g. we could render the plugin with some mock-data and scale it down
- it would also be nice, if you could add the same plugins multiple times to the panel, but with different initial configuration. This would allow to compose new plugins out of simpler plugins!

**Comment by PeterKottas** [comment]
The whole UI package IMHO is best to be ignored and implemented on the user side for anything more important than a tech demo. What you have written here makes perfect sense, however, there can be a million other people with a million other ideas of how this should look. Imho we should just keep these as simple as possible and maintain it more like guidelines for people to create their own rather than something that should be used in production. Because if that's the case, there will be a myriad of weird UI intricacies people will want to support. I will close for now as I am cleaning up some old issues. I wouldn't have a problem with it at all if you want to implement this though. Imho the UI package should be as simple and good looking as it can be. This could potentially help with that.
