### ISSUE TITLE
custom breakpoints and columns

### ISSUE THREAD

**Issue by schuma7** [react-page/react-page#758]
In our webapp we're working with different breakpoints for mobile, tablet and desktop media queries. This leads to weird layout behaviours since the react-page cells break differently from our own components.

Is there a way to customize these breakpoints so that they fit the ones we've defined?

**Comment by PeterKottas** [comment]
The breakpoints are just CSS so you should be able to override those. Since we don't use scss (maybe we should) it will require some work to have the base breakpoints configurable.

**Comment by macrozone** [comment]
@PeterKottas i am also thinking about enabling customizing rows, cols and cells. Maybe in conjunction with unifying layout and content plugins.

So in my case for example, i would remove the css-driven default rows and cols and would replace them with styled-component driven ones. These could reuse the existing breakpoints from my project. We would pass col-size property to these cols, so that when the cols get resized, the component could adopt to this. We could also provide a property on rows or the editor that defines the number of columns (currently 12, which is still perfect for most cases)

**Comment by PeterKottas** [comment]
This sounds cautiously optimistic. I think it's a great chance to do something cool but it needs to be done quite well to ensure backward compatibility and stable API for the future. Also, the API should be well thought out from the get-go. I should be able to look at progress from time to time but I am swamped in other stuff atm so I can't commit to any proper help.
