### ISSUE TITLE
Plugin error boundaries

### ISSUE THREAD

**Issue by PeterKottas** [react-page/react-page#764]
This is one for deeper discussion I guess. I have faced an issue where one plugin was misbehaving, corrupting react rendering tree with an error being thrown. The obvious solution (that I implemented for the time being) was to surround the react page Editor with an error boundary. However, at that point, all I can do is erase the whole editor state and let clients start over (potentially making them lose the efforts they put into creating the content)

I am considering if it would make sense to include a default ErrorBoundary (on the core rather than plugin level). I think it's fairly easy to implement, however, it would require certain API to help modify the UI, content and also callbacks for errors being thrown for logging. I would very much value your opinion on this @macrozone . I can't say such an approach would be my first choice, but at the time of writing, I can't see any other way to prevent complete state corruption by at least isolating it to local level. I envision the default UI for such an error boundary would contain a button that would erase the plugin state to its initial state.

Let me know what you think. Cheers

**Comment by PeterKottas** [comment]
I think the main motivation/excuse (call it what you will :) ) is by having the plugin ecosystem, we are effectively rendering unreliable code from 3rd parties. Error boundary might be a reasonable course of action to mitigate such "risk".

**Comment by macrozone** [comment]
An error boundary around the editor would probably not make a big difference. As I understand your problem was that you had an editorState that made the editor (or one of its cell plugins) crash, so that only resetting the editorState could resolve the problem. What about a ErrorBoundary around each Cell ? so if the cell contains a plugin that crashes on a certain state, it would render an Error, similar to the "missing plugin", with a button to remove that plugin.


_personally_ i would not worry too much about missbehaving plugins, because in my use cases mostly all plugins are created for the project as they contain project-specific components (slate being the only exception). I therefore also prefer to facilitate plugin creation (like i did with the schema-driven create-plugin package) instead of having a plugin ecosystem.

**Comment by PeterKottas** [comment]
I think you skipped over some parts I wrote cause 

> What about a ErrorBoundary around each Cell?

That is exactly what I proposed :) Yes, functionality similar to the missing plugin is what I am after. I am in the same situation, all plugins are inhouse, but I wonder how many people out there use 3rd party plugins. Or tbh, if there even are 3rd party plugins. Weirdly, for 8k stars, there doesn't seem to be much of an ecosystem. 

I think maybe we can keep this open and see if there are any "buyers" for the idea. I will implement this on my side on the plugin component level for the time being.

**Comment by macrozone** [comment]
I added an error boundary for plugins some versions ago! sorry forgot to mention here

**Comment by zehawki** [comment]
> Weirdly, for 8k stars, there doesn't seem to be much of an ecosystem.

Yup, I'm also really puzzled about this.

**Comment by PeterKottas** [comment]
At first, it might seem that way. But consider this. First of all, most stars here are by people who simply like the product, tested the demo, found it interesting, and starred it. However, there is a relatively small market for companies that actually create a product that requires this and use it on daily basis. That means the amount of contributions is relatively small. Or to be more precise, you are much more likely to see a small number of people contributing a huge amount of work as opposed to a lot of people contributing small chunks. That's just the nature of the product. 

Lastly, while there exist a number of plugins (we in GuestBell developed quite a few), these are more than likely very very specific to business needs and nobody has a real reason or motivation to share them. @zehawki hope that helps wrap your head around this because I agree, 8k stars with so little activity looks weird at first;)

**Comment by macrozone** [comment]
> At first, it might seem that way. But consider this. First of all, most stars here are by people who simply like the product, tested the demo, found it interesting, and starred it. However, there is a relatively small market for companies that actually create a product that requires this and use it on daily basis. That means the amount of contributions is relatively small. Or to be more precise, you are much more likely to see a small number of people contributing a huge amount of work as opposed to a lot of people contributing small chunks. That's just the nature of the product.
> 
> Lastly, while there exist a number of plugins (we in GuestBell developed quite a few), these are more than likely very very specific to business needs and nobody has a real reason or motivation to share them. @zehawki hope that helps wrap your head around this because I agree, 8k stars with so little activity looks weird at first;)

I also want to add some thoughts

as mentioned in https://github.com/react-page/react-page/issues/806#issuecomment-784946777 and as @PeterKottas already pointed out is that CellPlugins are highly business dependent. We also have like 30-40 different CellPlugins on one of our project, but they are not worth sharing, they all have a simple `type: "autoform"` controls, but they Renderer is a Component that is specific for the app (an online shop), like Product sliders, Text teasers, Videos, info boxes, brands sliders, quote blocks, etc.

That's also why I don't think it makes much sense to encourage people to share CellPlugins in the community. What I think make sense instead, is to make it as easy, simple and flexible as possible to define CellPlugins. That is also why one of my first contributions to this Project here was to add a mechanism to create Plugins with Schema-based controls.

Other CellPlugins like the Background Plugin have very sophisticated, but internally compicated controls and were developed way before `type: "autoform"` was a thing, but my dream is that we can replicate the control of that plugin with a schema-based approach (e.g. add tabs to the autoform controls).

**About the word "plugin"**

I think the word `Plugin` is a bit misleading here, that's why i renamed it to `CellPlugin`. While working on a 1.0.0 release i also considered to rename it to `CellType`, but i hesitated as I did not want to mess too much with the terminology. But i want to revisit this in the future. `CellType` or even `BlockType` or similar better describe what these "CellPlugins" actually represent: it's what type of cells or blocks you can add to the content.

A "Plugin" on the other hand is something that adds or changes functionality of a software. These kind of plugins make much more sense to share, but at the moment we have no such mechanism and instead encourage to add new functionality to the core or add more configuration options

**On repo's activity**

I started contributing on the repo over a year ago and at that time it was nearly archived by the former contributors. We managed to get it handed over to the "community" and I actively contributed to it since then. I used it in bigger, commercial applications in production for a year now, but the activity on the repository was still low. At some point i started to prepare a "1.0.0" version, as I believe "0.x.x" versions are not a good practise. I eventually merged it when i thought that its now good enough to go into proper semantic release cycle, but i did not expect to make much of a difference concerning the repo's activity. But i was wrong and i am very happy to see you guys raising issues and participating in discussions!

I also plan to make more advertisment for it in online communities, meetups or similar. I also invite you to do the same! 

I also think development ist now much more streamlined and simple after my big refactoring (HOCs too hooks, etc.), so advanced react devs should feel at home (again)

**Comment by zehawki** [comment]
> That's also why I don't think it makes much sense to encourage people to share CellPlugins in the community. 

I have a slightly different take on this. 

While it may not be useful to actually add community made plugins into the codebase, it might make sense to add gists, or add **working examples** to the docs. These are incredibly valuable since a lot of what we all do is based on software patterns, hence seeing working examples immediately gives ideas to a new comer about _whats possible_. After that its left to their imagination.

I intend to add plugins I'm creating into the docs, eg one I've created for adding buttons. Which is such an important little functionality.

> i am very happy to see you guys raising issues and participating in discussions!

I hope to be quite active here for a while, and drive a lot of usage [via my startup](https://www.maincross.net/topics/519/article/965/a-sweet-block-editor-has-come-to-town).

**Comment by macrozone** [comment]
> > That's also why I don't think it makes much sense to encourage people to share CellPlugins in the community.
> 
> I have a slightly different take on this.
> 
> While it may not be useful to actually add community made plugins into the codebase, it might make sense to add gists, or add **working examples** to the docs. These are incredibly valuable since a lot of what we all do is based on software patterns, hence seeing working examples immediately gives ideas to a new comer about _whats possible_. After that its left to their imagination.
> 
> I intend to add plugins I'm creating into the docs, eg one I've created for adding buttons. Which is such an important little functionality.
> 
> > Product sliders, Text teasers, Videos, info boxes, brands sliders, quote blocks, etc
> 
> I would simply love to see these by way of examples, unless they are propriety and cant be shared. Everyone needs this kind of stuff... and why reinvent the wheel if you've already created superb reusable blocks.
> 
> > i am very happy to see you guys raising issues and participating in discussions!
> 
> I hope to be quite active here for a while, and drive a lot of usage [via my startup](https://www.maincross.net/topics/519/article/965/a-sweet-block-editor-has-come-to-town).

i agree that we should have more examples! Gists are also highly welcomed! 

> eg one I've created for adding buttons

can you elaborate that?

> I would simply love to see these by way of examples, unless they are propriety and cant be shared. 

They are rather boring 😅

The product slider is very similar to the example: https://github.com/react-page/react-page/blob/master/examples/pages/examples/reactadmin.tsx#L171

We have a product slider in one of our projects: https://www.veloplus.ch/kompetenz/eigenprodukte/velopflege-petrus (scroll down)

This is literally the definition of that plugin (i guess its ok if i share this):

```
import { CellPlugin } from "@react-page/editor";

import React from "react";
import styled from "styled-components";
import ProductSlider from "../../../product/components/ProductSlider";
import ProductSliderItem from "../../../product/components/ProductSliderItem";
import { pluginBaseStyle } from "../../utils/pluginBaseStyle";

const Base = styled.div`
  ${pluginBaseStyle};
`;

const Renderer = ({ data: { title, productIds } }) => {
  return (
    <Base>
      <ProductSlider title={title} backgroundColor="sand">
        {productIds?.map((productId) => (
          <ProductSliderItem
            key={`slider-item-${productId}`}
            productId={productId}
          />
        ))}
      </ProductSlider>
    </Base>
  );
};

const plugin: CellPlugin<{
  title: string;
  productIds: string[];
}> = {
  Renderer,
  id: "productSlider",
  version: 1,
  title: "Product Slider",
  description: "Product Slider",
  controls: {
    type: "autoform",
    columnCount: 1,
    schema: {
      required: ["title", "productIds"],
      properties: {
        title: {
          type: "string",
          default: "Produkte",
        },
        productIds: {
          type: "array",

          items: {
            type: "string",
          },
        },
      },
    },
  },
};

export default plugin;

``` 


> I hope to be quite active here for a while, and drive a lot of usage via my startup.

looking forward to it!

<img width="608" alt="Bildschirmfoto 2021-02-24 um 12 53 12" src="https://user-images.githubusercontent.com/1972353/108996894-438b1c80-769f-11eb-8fb5-a66fdb4a584a.png">

i am flattered ;-)

**Comment by zehawki** [comment]
> i agree that we should have more examples! Gists are also highly welcomed!
> 
>     eg one I've created for adding buttons
> 
> can you elaborate that?
> 

Added here #913, will also submit via a PR into docs
