### ISSUE TITLE
can not install on React-17.0.1

### ISSUE THREAD

**Issue by jerome-diver** [react-page/react-page#921]
I can not install on React-17.0.1 due to unresolved dependencies.

**To Reproduce**
1. Install react-17.0.1
2. install @react-page/editor (even if @beta version)

**Expected behavior**
It should install package, but npm provide an error message asking for React-16.8.0 from @uniforms@3.2.0

**Desktop (please complete the following information):**
 - OS: ArchLinux

And after to npm install --force command passed to force install, import or @react-page/editor show a dependency error: missing @material-ui/icons/ [Error, CloudUpload, and so on...]

**Comment by macrozone** [comment]
these are two different things:

- it works with react 17.0.1 (in fact the examples run on that react version), but some libraries might yield an unmatched peer dependency warning, alltough they work without problems. In case of uniforms this will be solved soon: https://github.com/vazco/uniforms/issues/859
- missing `@material-ui/icons/ ` is because you have to install it separatly as described here https://react-page.github.io/docs/#/quick-start?id=getting-started

i would prefer to have material-ui not as a peer dependency but an ordinary dependency, but this might lead to problems if your app itself uses material-ui as multiple versions of material-ui lead to strange problems. I hope that future versions of material-ui solve this problem. 

Notice that @material-ui is only loaded if its really needed, so do not worry too much about bundle size.
