### ISSUE TITLE
plugin auto close when click outside.

### ISSUE THREAD

**Issue by dangdn** [react-page/react-page#934]
- I create editor plugin using TinyMCE. When I select on Menubar of Editor then BottomToolbar  auto close. I cann't work on Editor.

**Expected behavior**
- Can edit on editor and confirm when submit.

Please help me..... :((((

https://drive.google.com/file/d/1XvtgWkx2fzbvPjNtjiC5Ls6JMKe0Gihc/view

**Comment by macrozone** [comment]
@dangdn did you solve your problem?

**Comment by macrozone** [comment]
thats actually an interesting editor, in particular the table function.

Maybe we can add tables to the default slate text editor we provide, because that might be a bit more ergonimic (you don't have to open a separate window and can just work inline).

Are there other features that you miss on the slate plugin we provide?
