### ISSUE TITLE
Is there a way to insert component state value into Slate cell and keep them synced

### ISSUE THREAD

**Issue by rexebin** [react-page/react-page#938]
We could use a custom cell plugin to inject form values into the Slate cell like the `Link` example, but what if I want to insert the same link and text in multiple places and want to sync them?

I have this requirement, say I have a contract template and I need to be able to insert counter party's name in multiple places, what I want is that I have a select controller outside of the react-page editor, then maybe I could write a cell plugin to insert selected counter party's name in multiple places. Then when I select a different counterparty, the names in the cell should all update. 

Thank you for your help!

**Comment by macrozone** [comment]
You can use custom components in slate as well, so you can just use some hook to to load the data.

In fact we do this a lot, e.g. we have a PageLink where the editor-user can select a page from a repository and ReactPage just saves the id of that on the editor-state. When such a link is rendered, it fetches the page through a hook (apollo useQuery) and resolves the full path of that page (instead of the id).

similarly you can use any hook inside your slate component

**Comment by rexebin** [comment]
Thank you! I will try. Is there a recommended way for printing?

**Comment by macrozone** [comment]
> Thank you! I will try. Is there a recommended way for printing?

printing ? 🖨

**Comment by macrozone** [comment]
maybe follow this example: https://react-page.github.io/docs/#/slate?id=slate-plugins-with-custom-data

**Comment by macrozone** [comment]
> Like exporting to pdf ready for printing or sending off via email.

see https://github.com/react-page/react-page/discussions/920

**Comment by macrozone** [comment]
I close this since its more a question
