### ISSUE TITLE
Trouble focusing the Background plugin

### ISSUE THREAD

**Issue by avoskresensky** [react-page/react-page#945]
**Describe the bug**
Certain layouts make focusing the underlying background plugin unintuitive.

**To Reproduce**
1. Add a background plugin.
2. Add 4 plugins to it: two columns with two plugins each, one under another.
3. Make sure the columns are of uneven height
4. The blank space under the shortest column (within the background plugin) is not clickable. Clicks won't select the background plugin.

![image](https://user-images.githubusercontent.com/10179521/113563459-961ff880-95bc-11eb-9a7c-247e1f7ccc05.png)

Another strange (and maybe related) thing about this layout is that if you leave only one plugin in a column, it will consume the entire height of the column.

![image](https://user-images.githubusercontent.com/10179521/113563611-dda68480-95bc-11eb-83d0-81cc0a0e7db5.png)

**Comment by macrozone** [comment]
I know this problem, so i introduced these "tabs":

<img width="934" alt="Bildschirmfoto 2021-04-05 um 12 22 19" src="https://user-images.githubusercontent.com/1972353/113564375-94c8ed00-9609-11eb-9f88-17fe2d9c38ef.png">

problem is, that if you specify "overflow: hidden" on your background plugin, you won't see it.


The stretching of the cells to fill the parent is intentional, without it dragging and dropping cells next to these cells might be awkward, at least i think i did it because of that (should have documented it as an issue though).

Having said that, i also don't fully like the current solution, so the idea i have is to show the full hierarchy of the selected cell as tabs in the bottom toolbar (or in a similar way) and you can select any parent directly.

So something like:

`[ **Image** ] [ Background ]`


(or any other parents if its deeply nested)

Additionaly we could allow to select rows (or non-plugin cells) as well. This way we could also move / duplicate / delete rows. This might be handy if we have configurable rows.

Also we could enable to select "non-plugin" cells as well (the ones that lead to this issue: https://github.com/react-page/react-page/issues/943)

So the full hierarchy on the left is actually (if you would select one of the images):


`[ **Image** ][Row][Cell][Row][ Background ]`

**Comment by avoskresensky** [comment]
@macrozone, I have two problems with this artificial "stretching" at this point. Firstly, it's inconsistent: on the second screenshot it's present, but on the first one it doesn't really stretch -- it just prevents the clicks from selecting the containing layout plugin I guess.

Secondly, some of our plugins have chrome (cards with box-shadow, borders, backgrounds etc), so we absolutely can't have cells deciding to stretch on their own. So I'd like to understand which element exactly does that and how to suppress it with CSS if possible at all.

As for the drag and drop woes, we're musing on creating another page-level UI element: a drawer that shows a tree of all plugins (call it "layers" maybe). Users will be able to find and select elusive small plugins there, see entire structure and, given grag and drop support, rearrange the tree and/or even drop new plugins into that tree.

**Comment by macrozone** [comment]
you still can decide whether a cell fills up the space. I used that a lot (e.g. cards that have an equal height in a row).

a Row has a height based on its content, the cells in the row have all the same height (flex stretch) and the inner cells fill up the space until your plugin's component. If you specify `height: 100%` on that, it will fill up the space and if you do not set it, it will not fill up the space

It would not fix the click problem anyway, you will always click on a row. We could need to add `pointer-events: none` to some elements in order to fix that, but that might have negative side effects.

the tree is a good idea, I would appreciate it if you could open source it here (as package or core feature)!

**Comment by avoskresensky** [comment]
@macrozone, so looked into the "click problem" and here's what I found:

Firstly, the click event is being stopped here:
https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Cell/index.tsx#L130

This one seems to be pretty easy to fix by changing it to `onClick={stopClick(hasPlugin && isEditMode)}`
That takes care of bubbling, but the event doesn't pass the checks here:

https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Cell/Inner/index.tsx#L41

In order for it to pass something needs to be done to those .react-page-cell and .react-page-row checks.
The first one seems easy:

```
target.closest('.react-page-cell.react-page-cell-has-plugin') === ref.current.closest('.react-page-cell')
```

... does the trick.

As for the row check -- I don't know what to do with it, since I don't understand why it's there in the first place.
Commenting it out makes the whole thing work for me, but I'm sure I'm missing some corner case.

**Comment by avoskresensky** [comment]
@macrozone, couple of PSs:

When I make the above changes, it works, but not exactly as other plugins. When I click the first time, it focuses and the drawer shows up, but when I click the second time, it disappears. That happens because of this call:

https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Row/index.tsx#L61

... which fires because the event passes the row boundary while bubbling.
I don't quite understand why this call is made there, but maybe it should be conditional.

Another note: from the performance optimization perspective, it seems strange that in this `if`

https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Cell/Inner/index.tsx#L38

... the "cheapest" conditions (local variables, `target.classList`) are at the end, while the first thing we do is dig inside the DOM.

**Comment by macrozone** [comment]
> @macrozone, couple of PSs:
> 
> When I make the above changes, it works, but not exactly as other plugins. When I click the first time, it focuses and the drawer shows up, but when I click the second time, it disappears. That happens because of this call:
> 
> https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Row/index.tsx#L61
> 
> ... which fires because the event passes the row boundary while bubbling.
> I don't quite understand why this call is made there, but maybe it should be conditional.

probably a relict, i don't think its needed there?


> 
> Another note: from the performance optimization perspective, it seems strange that in this `if`
> 
> https://github.com/react-page/react-page/blob/a454b9f7a1a00319125e1c0ffb25ca624b81f98b/packages/editor/src/core/components/Cell/Inner/index.tsx#L38
> 
> ... the "cheapest" conditions (local variables, `target.classList`) are at the end, while the first thing we do is dig inside the DOM.

that does not really matter performance wise, but you can swap it if you like

**Comment by avoskresensky** [comment]
@macrozone, 

> As for the row check -- I don't know what to do with it, since I don't understand why it's there in the first place.
> Commenting it out makes the whole thing work for me, but I'm sure I'm missing some corner case.

Any insight?

**Comment by macrozone** [comment]
> @macrozone,
> 
> > As for the row check -- I don't know what to do with it, since I don't understand why it's there in the first place.
> > Commenting it out makes the whole thing work for me, but I'm sure I'm missing some corner case.
> 
> Any insight?

don't know honestly.

**Comment by avoskresensky** [comment]
@macrozone 
Well, I'm going to try to find a reason for its existence, but if I don't I'm just going to comment it out and send you a PR. Okay?

**Comment by avoskresensky** [comment]
> I'm going to try to find a reason for its existence

The reason for its existence was dealing with resize-handle clicks and drags.
I think I found a better way of handling this.
